image: $REPO_URL/stage

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - trigger

variables:
  DOCKER_HOST: tcp://localhost:2375/
  BASE_IMAGE_NAME: polyswarmd-config

default:
  before_script:
    - pip install -q --upgrade pip
    - pip install -q $END_TO_END_LIB@$CI_COMMIT_REF_NAME || pip install -q $END_TO_END_LIB
    - e2e init

###############################################################
# Build Stage (jobs inside a stage run in parallel)
###############################################################
dev-pypi:
  tags:
    - kube
  stage: build
  before_script:
    - pip3 install -q --upgrade pip setuptools twine wheel bump2version
  script:
    - SHORT_SHA=$(git rev-parse --short HEAD) bumpversion --no-commit --no-tag local
    - python setup.py -q bdist_wheel
    - twine upload --skip-existing --disable-progress-bar --non-interactive dist/*

build-linux:
  stage: build
  tags:
    - kube
  script:
    - docker pull $REPO_URL/$BASE_IMAGE_NAME:latest || true
    - docker build
      --pull
      -f docker/Dockerfile
      -t $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_SHA
      -t $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_REF_SLUG
      --cache-from=$REPO_URL/$BASE_IMAGE_NAME:latest
      .
    - docker push $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_REF_SLUG

###############################################################
# Test Stage
###############################################################
test-py36:
  image: python:3.6
  stage: test
  tags:
    - kube
  before_script:
    - pip3 install tox
  script:
    - tox -e py36
  except:
    - images

test-py35:
  image: python:3.7
  stage: test
  tags:
    - kube
  before_script:
    - pip3 install tox
  script:
    - tox -e py37
  except:
    - images

###############################################################
# Release Stage
###############################################################
release-latest:
  stage: release
  tags:
    - kube
  script:
    - docker pull $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $REPO_URL/$BASE_IMAGE_NAME:$CI_COMMIT_SHA $REPO_URL/$BASE_IMAGE_NAME:latest
    - docker push $REPO_URL/$BASE_IMAGE_NAME:latest
  only:
    - master

release-pypi:
  tags:
    - kube
  stage: release
  script:
    # release to internal pypi but do not tag yet
    - e2e release --skip-tag --remote https://github.com/polyswarm/$CI_PROJECT_NAME.git
    # release to public pypi and tag
    - e2e release
      -u $PUBLIC_TWINE_USERNAME
      -p $PUBLIC_TWINE_PASSWORD
      -r $PUBLIC_TWINE_REPOSITORY_URL
      --remote https://github.com/polyswarm/$CI_PROJECT_NAME.git


###############################################################
# Trigger other CI builds
###############################################################

rebuild-polyswarmd-fast-artifacts:
  stage: trigger
  only:
    - master
  trigger: externalci/polyswarmd-fast-artifacts
  variables:
    BASE_IMAGE_NAME: polyswarmd-fast-artifacts

rebuild-polyswarmd-fast-events:
  stage: trigger
  only:
    - master
  trigger: externalci/polyswarmd-fast-events
  variables:
    BASE_IMAGE_NAME: polyswarmd-fast-events
